name: Postgres.app
description: "Postgres.app is a full featured PostgreSQL installation packaged as a standard Mac app."

gems: ['jekyll-github-metadata']
repository: postgresapp/postgresapp

downloadLocation: https://github.com/PostgresApp/PostgresApp/releases/download/9.6.1/Postgres-9.6.1.zip
postgresqlVersion: 9.6.1
postgisVersion: 2.3.0

downloadLocation93: https://github.com/PostgresApp/PostgresApp/releases/download/9.3.15/Postgres-9.3.15.zip
postgresqlVersion93: 9.3.15
postgisVersion93: 2.1.8

downloadLocation94: https://github.com/PostgresApp/PostgresApp/releases/download/9.4.10/Postgres-9.4.10.zip
postgresqlVersion94: 9.4.10
postgisVersion94: 2.1.8

downloadLocation95: https://github.com/PostgresApp/PostgresApp/releases/download/9.5.5/Postgres-9.5.5.zip
postgresqlVersion95: 9.5.5
postgisVersion95: 2.2.3

downloadLocation96: https://github.com/PostgresApp/PostgresApp/releases/download/9.6.1/Postgres-9.6.1.zip
postgresqlVersion96: 9.6.1
postgisVersion96: 2.3.0


languages: [en, de]
